// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/profile/:playerId": {
    params: {
      "playerId": string;
    };
  };
  "/upgrades/:playerId": {
    params: {
      "playerId": string;
    };
  };
  "/game": {
    params: {};
  };
  "/api/save-progress": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/profile/:playerId" | "/upgrades/:playerId" | "/game" | "/api/save-progress";
  };
  "routes/player-select.tsx": {
    id: "routes/player-select";
    page: "/";
  };
  "routes/profile.$playerId.tsx": {
    id: "routes/profile.$playerId";
    page: "/profile/:playerId";
  };
  "routes/upgrades.$playerId.tsx": {
    id: "routes/upgrades.$playerId";
    page: "/upgrades/:playerId";
  };
  "routes/game.tsx": {
    id: "routes/game";
    page: "/game";
  };
  "routes/api.save-progress.tsx": {
    id: "routes/api.save-progress";
    page: "/api/save-progress";
  };
};